"""Best-effort Terraform (HCL) rendering for a proposed AccountNetworkPolicy.

`--export` writes the proposed policy as JSON (a curl / REST body) and, alongside it, a Terraform
config. The Databricks provider's resource/attribute names for account network policies are newer and
may differ by provider version, so the HCL is a *starting point to review* — not guaranteed to
`terraform apply` unchanged.
"""

from __future__ import annotations

import re

RESOURCE_TYPE = "databricks_account_network_policy"


def _tf_name(policy_id: str) -> str:
    """A Terraform-safe resource label derived from the policy id."""
    name = re.sub(r"[^a-zA-Z0-9_]", "_", policy_id or "").strip("_")
    if not name or not re.match(r"[a-zA-Z_]", name):
        name = f"np_{name}" if name else "network_policy"
    return name


def _scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def _lines(obj: dict, indent: int) -> list[str]:
    pad = "  " * indent
    out: list[str] = []
    for key, val in obj.items():
        if val is None or (isinstance(val, (list, dict)) and not val):
            continue  # omit nulls and empties
        if isinstance(val, dict):
            out.append(f"{pad}{key} {{")
            out += _lines(val, indent + 1)
            out.append(f"{pad}}}")
        elif isinstance(val, list) and all(isinstance(i, dict) for i in val):
            # list of objects -> a repeated nested block per item (the Terraform idiom)
            for item in val:
                out.append(f"{pad}{key} {{")
                out += _lines(item, indent + 1)
                out.append(f"{pad}}}")
        elif isinstance(val, list):
            out.append(f"{pad}{key} = [{', '.join(_scalar(i) for i in val)}]")
        else:
            out.append(f"{pad}{key} = {_scalar(val)}")
    return out


def network_policy_hcl(policy: dict) -> str:
    """Best-effort `databricks_account_network_policy` HCL for the proposed policy dict (from
    AccountNetworkPolicy.as_dict()). account_id is dropped — the provider supplies it."""
    pid = policy.get("network_policy_id") or "network_policy"
    body = {k: v for k, v in policy.items() if k != "account_id"}
    header = [
        "# Best-effort Terraform generated by dbx-nwp-helper — REVIEW before `terraform apply`.",
        f"# Targets the `{RESOURCE_TYPE}` resource; attribute/block names for account network",
        "# policies are newer and may differ by Databricks provider version.",
        f'resource "{RESOURCE_TYPE}" "{_tf_name(pid)}" {{',
    ]
    return "\n".join(header + _lines(body, 1) + ["}"]) + "\n"
